baseURL = "https://www.elisedaniellemarion.ca/"
languageCode = "en-us"
title = "Elise Danielle Marion"

author = "Elise Danielle Marion"
description = "A portfolio site of Elise Danielle Marion"
defaultContentLanguage = "en"

paginate = 9  # Optional: adjust based on the number of items per page

[permalinks]
  gallery = "/:section/:title/"

[params]
  description = "Exploring the Intersection of Literature & Technology."

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


enableGitInfo = true
disableHugoGeneratorInject = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

[social]
  github = "https://github.com/blondieslays"
  linkedin = "https://www.linkedin.com/in/elisedaniellemarion/"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

